// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xXxYeetroom2000xXx.Data;

namespace xXxYeetroom2000xXx.Migrations
{
    [DbContext(typeof(YeetroomContext))]
    partial class YeetroomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("xXxYeetroom2000xXx.Models.Kommentar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<string>("Eintrag")
                        .HasColumnType("text");

                    b.Property<int>("Post_ID")
                        .HasColumnType("int");

                    b.Property<string>("Verfasser")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Kommentar");
                });

            modelBuilder.Entity("xXxYeetroom2000xXx.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<string>("Eintrag")
                        .HasColumnType("text");

                    b.Property<string>("Verfasser")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Forumeinträge");
                });
#pragma warning restore 612, 618
        }
    }
}
